default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rubis_project_app_development
  username: postgres
  password: 1234
  host: rubis_project_app-develop-db-1
  port: 5432

test:
  <<: *default
  database: rubis_project_app_test

production:
  <<: *default
  database: rubis_project_app_production
  username: rubis_project_app
  password: <%= ENV["RUBIS_PROJECT_APP_DATABASE_PASSWORD"] %>
